sudo: false
language: php
php:
  - '5.3'
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  include:
    - php: '5.3'
      dist: precise

install:
  - cat composer.json
  - composer self-update
  - rm composer.lock
  - composer install -o --profile

script: vendor/bin/phpunit
